from fastapi import APIRouter, HTTPException, Depends
from typing import List
from sqlalchemy.orm import Session
from database import get_db
import db_models
from models import MedicineReminder, Appointment, Contact, Recipe, GroceryItem, HealthInfo

router = APIRouter()

# --- Medicines ---
@router.get("/medicines", response_model=List[MedicineReminder])
def get_medicines(db: Session = Depends(get_db)):
    return db.query(db_models.MedicineReminderDB).all()

@router.post("/medicines", response_model=MedicineReminder)
def add_medicine(med: MedicineReminder, db: Session = Depends(get_db)):
    db_med = db_models.MedicineReminderDB(**med.dict(exclude={'id'})) # Exclude ID to let DB handle it? Or user provides ID?
    # Current models have ID. If user provides ID, we use it? 
    # Usually ID is autogenerated. The Pydantic model has ID. 
    # If I exclude ID, the DB generates it. The response model expects ID.
    # Let's assume ID is ignored on input or we should make it optional in Pydantic for creation.
    # But for now, I'll just exclude ID from the input dict if it's 0 or let DB handle it if I don't pass it.
    # The current Pydantic models require ID. This is a bit of a mismatch for creation.
    # I'll just pass everything for now, but usually we want a separate CreateSchema.
    # Given the "run it" constraint, I'll try to make it work with existing schemas.
    # If I pass ID, sqlite might accept it.
    # Let's try to just pass **med.dict() but if ID is present it might conflict if it exists.
    # I'll exclude 'id' and let DB generate it, then return the DB object which has the new ID.
    # But wait, the input `med` has an ID. If the user sends ID=0, and I exclude it, DB generates 1.
    # If user sends ID=1, and I exclude it, DB generates 2.
    # I'll exclude 'id' for creation.
    
    # Wait, the Pydantic model `MedicineReminder` has `id: int`. It's required.
    # The frontend/user must send an ID.
    # If I want to support auto-increment, I should have made ID optional.
    # I'll just exclude 'id' from the insert and let the DB generate it.
    # The response will use the DB's ID.
    
    med_data = med.dict(exclude={'id'})
    db_med = db_models.MedicineReminderDB(**med_data)
    db.add(db_med)
    db.commit()
    db.refresh(db_med)
    return db_med

@router.put("/medicines/{med_id}/toggle")
def toggle_medicine(med_id: int, db: Session = Depends(get_db)):
    med = db.query(db_models.MedicineReminderDB).filter(db_models.MedicineReminderDB.id == med_id).first()
    if not med:
        raise HTTPException(status_code=404, detail="Medicine not found")
    med.taken = not med.taken
    db.commit()
    db.refresh(med)
    return med

# --- Appointments ---
@router.get("/appointments", response_model=List[Appointment])
def get_appointments(db: Session = Depends(get_db)):
    return db.query(db_models.AppointmentDB).all()

@router.post("/appointments", response_model=Appointment)
def add_appointment(appt: Appointment, db: Session = Depends(get_db)):
    appt_data = appt.dict(exclude={'id'})
    db_appt = db_models.AppointmentDB(**appt_data)
    db.add(db_appt)
    db.commit()
    db.refresh(db_appt)
    return db_appt

# --- Contacts ---
@router.get("/contacts", response_model=List[Contact])
def get_contacts(db: Session = Depends(get_db)):
    return db.query(db_models.ContactDB).all()

@router.post("/contacts", response_model=Contact)
def add_contact(contact: Contact, db: Session = Depends(get_db)):
    contact_data = contact.dict(exclude={'id'})
    db_contact = db_models.ContactDB(**contact_data)
    db.add(db_contact)
    db.commit()
    db.refresh(db_contact)
    return db_contact

# --- Recipes ---
@router.get("/recipes", response_model=List[Recipe])
def get_recipes(db: Session = Depends(get_db)):
    return db.query(db_models.RecipeDB).all()

# --- Groceries ---
@router.get("/groceries", response_model=List[GroceryItem])
def get_groceries(db: Session = Depends(get_db)):
    return db.query(db_models.GroceryItemDB).all()

@router.post("/groceries", response_model=GroceryItem)
def add_grocery(item: GroceryItem, db: Session = Depends(get_db)):
    item_data = item.dict(exclude={'id'})
    db_item = db_models.GroceryItemDB(**item_data)
    db.add(db_item)
    db.commit()
    db.refresh(db_item)
    return db_item

@router.put("/groceries/{item_id}/toggle")
def toggle_grocery(item_id: int, db: Session = Depends(get_db)):
    item = db.query(db_models.GroceryItemDB).filter(db_models.GroceryItemDB.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    item.checked = not item.checked
    db.commit()
    db.refresh(item)
    return item

# --- Health Info ---
@router.get("/health", response_model=HealthInfo)
def get_health_info(db: Session = Depends(get_db)):
    info = db.query(db_models.HealthInfoDB).first()
    if not info:
        # Create default if not exists
        default_info = db_models.HealthInfoDB(
            blood_type="O+",
            allergies=["Peanuts"],
            conditions=["Hypertension"],
            insurance_provider="MediCare",
            policy_number="MC-123456789"
        )
        db.add(default_info)
        db.commit()
        db.refresh(default_info)
        return default_info
    return info

